App\Entity\Product:
  properties:
    name:
      - NotBlank: { message: "Le nom du produit est obligatoire" }
      - Length:
          {
            min: 3,
            max: 255,
            minMessage: "Le nom du produit doit depasser 3 carractaires",
          }
    price:
      - NotBlank: { message: "Le prix du produit est obligatoire "}